### ISSUE TITLE
Munge in container won't start

### ISSUE THREAD

**Issue by XueCangQiuYe** [dun/munge#101]
Hello, sorry to bother you.

In server A, I already installed munge in container, and I can use `systemctl start munge` to start munge, it works fine. Then I commit container to docker image. I use `docker run -d --privilieged 'image' /usr/sbin/init` to start a container to check munge's status, and it works fine. So I use `docker save -i munge.tar ''image` to save this image and send it to server B.

In server B, I use `docker load -i munge.tar` and start a container, but munge won't start.

```shell
[root@c33605fe4378 /]# systemctl status munge

● munge.service - MUNGE authentication service

   Loaded: loaded (/usr/lib/systemd/system/munge.service; enabled; vendor preset: disabled)

   Active: activating (start) since Tue 2021-04-27 10:24:48 UTC; 11s ago

     Docs: man:munged(8)

  Process: 249 ExecStart=/usr/sbin/munged (code=exited, status=0/SUCCESS)

   CGroup: /system.slice/docker-c33605fe4378a4fa519d3a6344bac62903244a70bf7c30af46a8c39f2c10e8c3.scope/system.slice/munge.service

           └─254 /usr/sbin/munged

 

Apr 27 10:24:48 c33605fe4378 systemd[1]: Starting MUNGE authentication service...

Apr 27 10:24:48 c33605fe4378 systemd[1]: New main PID 254 does not belong to service, and PID file is not owned by root. Refusing.

Apr 27 10:24:48 c33605fe4378 systemd[1]: New main PID 254 does not belong to service, and PID file is not owned by root. Refusing.

 
[root@c33605fe4378 /]# munged

munged: Error: Logfile is insecure: "/var/log/munge/munged.log" should be owned by UID 0


[root@c33605fe4378 /]# ll /var/run/

total 20

drwxr-xr-x  2 root  root     40 Apr 27 10:24 console

drwx------  2 root  root     40 Apr 27 10:24 cryptsetup

drwxr-xr-x  2 root  root     60 Apr 27 10:24 dbus

drwxr-xr-x  2 root  root     40 Apr 27 10:24 faillock

drwx--x---  3 root  apache   60 Apr 27 10:24 httpd

-rw-r--r--  1 root  root      3 Apr 27 10:24 incrond.pid

drwxr-xr-x  4 root  root     80 Apr 27 10:24 lock

drwxr-xr-x  2 root  root     40 Apr 27 10:24 log

drwxr-xr-x  2 root  root     40 Apr 27 10:24 mount

drwxr-xr-x  2 munge munge   100 Apr 27 10:38 munge

drwxrwxr-x  2 root  root     40 Apr 27 10:24 netreport

drwx------  2 rpc   rpc      40 Apr 27 10:24 rpcbind

-r--r--r--  1 root  root      0 Apr 27 10:24 rpcbind.lock

srw-rw-rw-  1 root  root      0 Apr 27 10:24 rpcbind.sock

drwxr-xr-x  2 root  root     40 Apr 27 10:24 samba

drwxr-xr-x  2 root  root     40 Apr 27 10:24 sepermit

drwxr-xr-x  2 root  root     40 Apr 27 10:24 setrans

-rw-r--r--  1 root  root      4 Apr 27 10:26 slurmdbd.pid

-rw-r--r--  1 root  root      4 Apr 27 10:24 sshd.pid

drwx--x--x  3 root  root     60 Apr 27 10:24 sudo

drwx------  2 root  root     40 Apr 27 10:24 svnserve

drwxr-xr-x 15 root  root    400 Apr 27 10:37 systemd

drwxr-xr-x  7 root  root    160 Apr 27 10:38 udev

drwxr-xr-x  2 root  root     40 Apr 27 10:24 user

-rw-rw-r--  1 root  utmp   1152 Apr 27 10:26 utmp

-rw-r--r--  1 root  root      4 Apr 27 10:24 ypserv.pid

 

[root@c33605fe4378 /]# ll /var/log/

total 1556

-rw-------  1 root  utmp                 0 Jan  6 06:08 btmp

-rw-r--r--  1 root  root            898060 Apr 27 10:24 dmesg

-rw-r--r--  1 root  root            219461 Jan 14 06:04 dmesg.old

-rw-r--r--. 1 root  root               193 Dec  4  2018 grubby_prune_debug

drwx------  2 root  root                 6 Nov 16 16:19 httpd

drwxr-sr-x+ 1 root  systemd-journal     46 Apr 27 10:24 journal

-rw-r--r--  1 root  root            324704 Jan  8 03:08 lastlog

drwx------  1 munge munge               24 Jan  7 09:42 munge

drwx------  3 root  root                17 Jan  6 06:11 samba

drwxr-xr-x  1 root  root                26 Apr 27 10:26 slurm

drwxr-xr-x  2 root  root                77 Jan  8 01:53 slurm-bak

-rw-------  1 root  root             71168 Jan  7 09:42 tallylog

-rw-rw-r--  1 root  utmp             28032 Apr 27 10:26 wtmp

-rw-------  1 root  root             36480 Jan 10 03:01 yum.log



[root@c33605fe4378 /]# ll /etc/munge/

total 4

-r-------- 1 munge munge 1024 Jan  7 09:41 munge.key

 

[root@c33605fe4378 /]# ll /var/lib/

total 0

drwxr-xr-x  1 root    root    36 Jan  8 01:49 alternatives

drwx------  2 apache  apache   6 Nov 16 16:19 dav

drwxr-xr-x  1 root    root    24 Jan  7 02:39 dbus

drwxr-xr-x  3 root    root    34 Jan  6 06:13 flatpak

drwxr-xr-x. 2 root    root     6 Apr 11  2018 games

drwxr-xr-x  2 geoclue geoclue  6 Oct 30  2018 geoclue

drwxr-xr-x  1 root    root     6 Sep 30  2020 initramfs

drwx------. 2 root    root     6 Dec  4  2018 machines

drwxr-xr-x. 2 root    root     6 Apr 11  2018 misc

drwx------  1 munge   munge   24 Apr 27 10:26 munge

drwxr-x---  3 root    polkitd 28 Jan  6 06:12 polkit-1

drwx------  2 pulse   pulse    6 Dec 15 16:39 pulse

drwx------  2 rpc     rpc      6 Apr  1  2020 rpcbind

drwxr-xr-x  1 root    root    54 Jan 14 06:04 rpm

drwxr-xr-x. 2 root    root     6 Apr 11  2018 rpm-state

drwxr-xr-x  4 root    root    33 Jan  6 06:11 samba

drwx------  4 slurm   slurm   90 Jan  7 09:30 slurm

drwxr-xr-x  4 root    root    35 Jan  6 06:08 stateless

drwxr-xr-x  1 root    root    25 Nov 16 16:46 systemd

drwx------  2 tss     tss      6 Aug  3  2017 tpm

drwxr-xr-x  1 root    root    55 Jan 10 03:01 yum

 
```

serverA
```shell
[root@cloudos-21 ~]# uname -srm

Linux 4.14.0-115.7.1.el7a.x86_64 x86_64
```
centos7.5

serverB
```shell
[root@c33605fe4378 /]# uname -srm

Linux 3.10.0-957.27.2.el7.x86_64 x86_64
```
centos7.6

**Comment by dun** [comment]
I've never tried running `munged` in docker.

The `munge.service` systemd configuration file runs `munged` as the "munge" user. This non-privileged user owns the directories `/etc/munge`, `/var/lib/munge`, `/var/log/munge`, and `/var/run/munge`.  Based on your output, those directories all appear to be correctly owned by "munge" with appropriate permissions.

I regularly test on CentOS 7 x86_64 (currently 7.9.2009) so that should be fine.

> Apr 27 10:24:48 c33605fe4378 systemd[1]: New main PID 254 does not belong to service, and PID file is not owned by root. Refusing.

Hmmm... That is curious.  It appears to be a docker bug caused by stricter PIDfile handling in systemd:
- https://github.com/systemd/systemd/issues/11752
- https://github.com/docker/for-linux/issues/835

If it's a problem with the PIDfile, you can have systemd run `munged` without it:

`# systemctl edit --system --full munge`
1. Change `Type=forking` to `Type=simple`
2. Change `ExecStart=/usr/sbin/munged` to `ExecStart=/usr/sbin/munged --foreground --syslog`
3. Delete `PIDFile=/var/run/munge/munged.pid`

After these changes, `systemctl start munge` will exec `munged` to run in the foreground instead of as a conventional double-forked backgrounded daemon process.  This should work ok.  There are some minor cosmetic issues with log messages being a bit strange; for example, they will be directed to syslog and appear with "munged: munged:" in the message.  This *might* work around the problem you're having.

> [root@c33605fe4378 /]# munged
> munged: Error: Logfile is insecure: "/var/log/munge/munged.log" should be owned by UID 0

The reason for this error is that you're attempting to start `munged` from the command-line as root, instead of starting it via `systemctl start munge` which would run it as the "munge" user.  Since `munged` is running as root, it detects `/var/log/munge/munged.log` is not owned by its uid (0) and fails with the above error.

To run it from the command-line as the "munge" user, you could try `runuser -m munge -c "munged -F"` or `sudo -u munge munged -F` -- the `-F` option runs it in the foreground so error messages are written to stderr which is helpful when troubleshooting.

**Comment by XueCangQiuYe** [comment]
Thank you for your reply.
I have tried, but munge still can't start.
```
# systemctl edit --system --full munge

Change Type=forking to Type=simple
Change ExecStart=/usr/sbin/munged to ExecStart=/usr/sbin/munged --foreground --syslog
Delete PIDFile=/var/run/munge/munged.pid
```
docker version on serverA is 1.13.1
docker version on serverB is 18.09.6
It seem to be a docker bug caused munge fail, so I installed munge in a container on serverB, and it works well.

So be it.
Thanks again for your reply.

**Comment by avatar-lavventura** [comment]
@dun  Hoping this help someone: I had to run as `nohup sudo -u munge munged -F &> /var/log/munged.log` to force `munge` to run in the background.

**Comment by dun** [comment]
@avatar-lavventura `SIGHUP` is ignored when `munged` backgrounds itself during the daemonization step, but doesn't get ignored when running with `--foreground`. I'll get that fixed in the next release. Thanks!

**Comment by avatar-lavventura** [comment]
@dun Sorry for writing this closed thread, I can open a new thread if neccessary. 

Please note that I also get following ```munged: Info: Unauthorized credential for client UID=0 GID=0``` warning message, but `munge` works fine.

I have following configurations in `Dockerfile`:

```bash
RUN /sbin/create-munge-key \
 && chown munge:munge -R /run/munge
```

and having following in my `docker-entrypoint.sh` file which runs when the container starts.

```bash
sudo chown munge:munge -R /run/munge  
nohup sudo -u munge munged -F > /var/log/munged.log &!
```

Seems like everything is fine but I have not able to figure out the solution for the warning message.

**Comment by dun** [comment]
@avatar-lavventura The "unauthorized credential" message happens when a credential is encoded with either a UID or GID restriction, and the process decoding the credential does not have a matching UID/GID. See `-u, --restrict-uid` and `-g, --restrict-gid` in [munge(1)](../wiki/Man-1-munge).

If you still have questions, please open a new issue for this discussion since we're getting off-topic from the original post. Thanks.
