### ISSUE TITLE
Exceeded maximum length of socket pathname

### ISSUE THREAD

**Issue by Tom-python0121** [dun/munge#106]
when i use:munge -n, some error happend.
### Steps to reproduce the issue

```console
[root@localhost sbin]# ./munged -S ../var/run/munge/munge.socket.2
[root@localhost sbin]# munge -n
-bash: munge: command not found
[root@localhost sbin]# cd ..
[root@localhost munge-0.5.14-226zewtxozsftf3gjc6ttnwskq4msqkj]# ls
bin  etc  include  lib  sbin  share  var
[root@localhost munge-0.5.14-226zewtxozsftf3gjc6ttnwskq4msqkj]# spack load munge
[root@localhost munge-0.5.14-226zewtxozsftf3gjc6ttnwskq4msqkj]# munge -n
munge: Error: Exceeded maximum length of socket pathname
```
Why would it happen?

**Comment by dun** [comment]
Communication with `munged` is over a UNIX domain socket. The pathname array in the `struct sockaddr_un` is 108 bytes. The path string you presumably passed to `configure --with-munge-socket=PATH` exceeds that maximum length.

**Comment by Tom-python0121** [comment]
@dun Is that what you mean? 
[root@localhost sbin]# ./munged --socket=../var/run/munge/munge.socket.2
[root@localhost sbin]# munge --socket=../var/run/munge/munge.socket.2


Why is it stuck here?It's not going down. It's stuck here.

**Comment by dun** [comment]
The `munge` `-n` command-line arg has nothing to do with the `Error: Exceeded maximum length of socket pathname`. You're getting that error because the software was configured with a socket name that exceeds the 108-byte static array. You can see the default socket name shown in brackets with: `./munged -h | grep socket=`

If you don't specify `-n` to `munge --socket=../var/run/munge/munge.socket.2`, the `munge` client will read from stdin until it gets an EOF -- it's not stuck. Try entering ctrl-d, or add `-n` to the `munge` command.
