### ISSUE TITLE
`/var/log/munge` is not created during startup

### ISSUE THREAD

**Issue by pat-s** [dun/munge#107]
I am running a virtual image for provisioning HPC nodes with a centos 7 base.

I've installed `munge` from EPEL7 but during node startup, `munge.service` always fails and complains that `/var/log/munge` is missing.

I am creating all required dirs `/var/log/munge` and `/var/run/munge` by hand since months and then restart the service which fixes the issue post-startup but I cannot figure out why the respective dirs are not created.

Slurm and other services create their respective log dirs just fine.

This issue seems a bit similar to #75 but I am not entirely sure.
Any help is appreciated so I might be able to do a clean boot at some point in the future :)

`munge-0.5.11-3.el7.x86_64`

**Comment by dun** [comment]
`/var/log/munge` is created during rpm package installation since `/var/log` is not traditionally a transient filesystem cleared at startup. I don't understand why you would need to re-create `/var/log/munge`. What is removing it?

`munged` cannot create this directory since it does not run as root.

In `munge-0.5.11-3.el7.x86_64`, `/var/run/munge` is created during rpm package installation, and also at boot by `/usr/lib/tmpfiles.d/munge.conf`.

I re-tested this just now with `munge-0.5.11-3.el7.x86_64` on a CentOS 7.9.2009 vm. `/var/log/munge` survives reboot, and `/var/run/munge` is re-created at boot by `tmpfiles.d`.

**Comment by pat-s** [comment]
Thanks!

I am installing `munge` in a virtual image via `chroot` (`yum -y --installroot=$CHROOT`) and in the root of the virtual image (`$CHROOT/var/log/munge`) `/var/log/munge` exists.

However, when finally booting the a node with the image, `/var/log/munge` does not exists and hence `munge` fails to start. I then need to recreate it within the node and restart the service.

It could be that this is unrelated to `munge` itself but given that `munge` is the only service having this problem with its log dir, I am wondering what I might be doing wrong 🤔 
I expect that all contents in `$CHROOT/var/log/munge` should be present within the image during boot as this is true for all other services. Am I making some kind of rookie mistake here and do I need to explicitly include `/var/log/munge` in the image in some other way?

**Comment by dun** [comment]
I don't know why `/var/log/munge` does not exist in the image. But you can recreate that directory with `tmpfiles.d` by appending `d /var/log/munge 0700 munge munge -` to `/usr/lib/tmpfiles.d/munge.conf`. That will create both directories at boot.
