### ISSUE TITLE
Error creating volatile directories on system startup when using LDAP as the user backend

### ISSUE THREAD

**Issue by mrolli** [dun/munge#114]
We are running a HPC cluster with munge and slurm. Since slurm requires in their documentation that the uidNumber and gidNumber for the user/group munge/slurm should be consistent, we recently decided to move these users and groups from local system files of the 360 nodes we have to our central LDAP-Server - the natural backend for users and groups that shall have consistent uidNumbers and gidNumbers across hundreds of nodes.

Apparently this is not supported and does not work since munge is using systemd-tmpfiles to create the volatile files/directories:

```
Jan 28 08:55:03 knode36 systemd: Starting Create Volatile Files and Directories...
Jan 28 08:55:03 knode36 systemd-tmpfiles: [/usr/lib/tmpfiles.d/munge.conf:1] Unknown user 'munge'.
Jan 28 08:55:03 knode36 systemd: systemd-tmpfiles-setup.service: main process exited, code=exited, status=1/FAILURE
Jan 28 08:55:03 knode36 systemd: Failed to start Create Volatile Files and Directories.
Jan 28 08:55:03 knode36 systemd: Unit systemd-tmpfiles-setup.service entered failed state.
```

By the time system-tmpfiles is run, there i no nslcd running to resolve the user. This leads to the following questions:

- Is it actually a requirement that the munge daemon is run using the same uidNumber on every host? The Slurm installation states this. Of no, then we would let CentOS decide about the uidNumber/gidNumber on package installation instead of bothering with this aspect.
- If it is a requirement, how could it be possible to have the munge user in ldap? Customize the sysmd service file of munge and add "After: nslcd.service"?
- Or what is your approach to the "Same uidNumber on every host"-task?

**Comment by dun** [comment]
It's recommended to run `munged` as a non-privileged user when possible (which is the case for any modern OS). For security, its UID/GID should be unique in order to restrict access to its keyfile and other sensitive directories. But there is no requirement for its UID/GID to be consistent across all nodes in a cluster (as long as `munged` can still access its local keyfile, etc.).

Re: Slurm, it's important for users submitting jobs to have consistent UID/GID numbers across the cluster, but I don't know why there would be such a requirement for the `munge` UID/GID.

As you suggested, you could try specifying `After: nslcd.service` in the `munge.service` config. I've never tested that. I'm curious to know if that would resolve this LDAP/nslcd ordering dependency problem without introducing another problem. Please follow-up here if you try it.

Our approach has been to distribute "configuration" files (including such things as `/etc/passwd`, `/etc/group`, etc.) using configuration-management tools such as Ansible, Chef, Puppet, CFEngine, rdist, etc.

**Comment by mrolli** [comment]
Thanks for your extensive answer. We use Puppet for deployment and are rolling out users/groups with the respective resources, which in tun run useradd and the like.

The `After: nslcd.service` approach wasn't thought through. It's `systemd-tmpfiles` that is generating the statedir and should run after `nslcd.service`, not (only) the `munge.service`, but I'll abstain from trying to delay that step. I'm afraid that would lead to other problems for sure.

Nevertheless, to still our curiosity, I tested the `After: nslcd.service` in `munge.service` approach and at least for the service order it works correctly:

```
Jan 29 09:11:56 anode252 nslcd[1551]: version 0.8.13 starting
Jan 29 09:11:56 anode252 systemd: Starting MUNGE authentication service...
...
Jan 29 09:12:01 anode252 nslcd[1551]: accepting connections
Jan 29 09:12:01 anode252 systemd: Started MUNGE authentication service.
Jan 29 09:12:01 anode252 systemd: Starting Slurm node daemon...
```

It actually appears as if the start of the `munge.service` is waiting for `nslcd` to become functional as it lasts 5s until `nslcd` is ready to accept connections and the message that munge has started comes afterwards, also 5s delayed to its starting message, but that could be a coincidence.

Thank you again. We will solve our issue by turning the ldap-based munge user/group back to a node-local user/group as documented, again deployed by Puppet as it was the case previously.

**Comment by dun** [comment]
Thanks for testing the `After: nslcd.service` and following-up. I'm glad to hear the Puppet approach will work for you.
