### ISSUE TITLE
Appropriate method of uninstalling so that I have a clean slate?

### ISSUE THREAD

**Issue by Dahlonega** [dun/munge#145]
Wise and powerful Dun, please bless this humble wannabe linux admin with your wisdom.

I have inherited a Rhel cluster that was using slurm. I recently had to upgrade it from rhel 7.9 to 8.10.

I am now trying to rebuild the cluster and would like to remove munge so that I can follow your installation walkthrough.

I briefly tried to get the existing install to work, However running 
```
munge -n | unmunge
munge: Error: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
unmunge: Error: No credential specified
```
there is a key on /etc/munge, however when I tried running 

`sudo -u munge /usr/sbin/mungekey --verbose
sudo: /usr/sbin/mungekey: command not found`

It seemed prudent to start over unless you recommend otherwise. What is the most appropriate way of setting myself up for success?

**Comment by dun** [comment]
Young Padawan @Dahlonega, I presume you have already succeeded in your quest to vanquish the old version since you've closed this issue. But for those traveling this path after you, I'll leave the following insights:

Since `/var/run/munge/munge.socket.2` was not found, `munged` was presumably not running. First check if `munged` is running, and if it's not, `sudo systemctl start munge`.

`mungekey` first appeared in 0.5.14. CentOS 7 and 8 had older versions, and the CentOS rpms included `/usr/sbin/create-munge-key`.

The munge rpm should be upgraded automatically as part of a complete upgrade from CentOS 7 to 8. If you wanted to start over, you could remove the existing package with `sudo dnf remove munge`, and then re-install with `sudo dnf install munge` -- but that shouldn't be necessary.

Remember, the greatest battles are fought within ourselves. May your courage and determination light the way to ultimate success.
