### ISSUE TITLE
compile time pathing vs command line pathing

### ISSUE THREAD

**Issue by mdidomenico4** [dun/munge#57]
can an option be put into the source to specify all the paths at command line rather then compile time.  currently the munge_defs.h assigns everything via the X_LOCALSTATDIR compiler flag.  it would be nicer if i could specifically override all those paths with flags on the command line instead.

**Comment by mdidomenico4** [comment]
or a config file specified on the command line, which includes directives for all the definitions.  like how slurm does it with slurm.conf

**Comment by dun** [comment]
Most of the paths from `munge_defs.h` can be overridden on the command-line at runtime:
- --socket
- --auth-server-dir
- --auth-client-dir
- --pid-file
- --key-file

The only two I see missing would be `--log-file` and `--seed-file`. Are these what you had in mind, or is there another path you need to override at runtime?

A config file is planned, but it's probably a few releases away yet since there's other functionality that needs to be added first.

**Comment by mdidomenico4** [comment]
yes those two would be sufficient for what i need.  I'm not sure if there are any other paths, i can't start up munge in the configuration I'm after because the compiled in paths don't exist.

I'm trying to have a shared installation of munge, where it's binaries are on an NFS share and the config is different based on which cluster it's running on but also located on the NFS share.

I need to define the paths to be unique at runtime.  I know this is atypical to the rpm, installed as a service, local to the box, but it's how I'd like my environment to be.

**Comment by dun** [comment]
I've added command-line options for `--log-file` and `--seed-file`. Please follow-up if these aren't sufficient.
