### ISSUE TITLE
munged sporadically dies ("Exiting on signal=15")

### ISSUE THREAD

**Issue by mbeeby** [dun/munge#63]
Dear all,

I wondered if anyone would be able to point me in the right direction to troubleshoot my munge daemon sporadically dying ("Exiting on signal=15")?

USUALLY the logs report this happening at 07:35:01 (or 07:35:02) on Mondays, Thursdays, and Sundays -- but not always! The length of time that munged runs before dying is not consistent either.

I have no idea what is killing munged, does anyone have any ideas how I could troubleshoot this?

many thanks,

Morgan

**Comment by dun** [comment]
With "Exiting on signal=15", munged has received a SIGTERM (signal number 15) and is shutting down as requested. My first thought was that the OOM Killer was terminating munged due to a low-memory situation; but I'd expect the OOM Killer to send a SIGKILL (signal number 9). I'm not sure what's going on here. All I can offer is that some other process (running as root or the same UID as munged) is requesting munged to terminate. Take a look at your crontab and see what is running at these times.

**Comment by mbeeby** [comment]
Hrm. Thanks for the quick response. I only have one thing in my root crontab, which is an hourly ZFS snapshot of a local SSD ZFS volume...

**Comment by dun** [comment]
Check your syslog for activity around 07:35 on Mon, Thr, and Sun.  For example, cron activity will be logged, but the file to which it is written will depend upon your distro and configuration.

You can use strace to capture the PID & UID of the process sending the SIGTERM. If you're on Linux, you can try using the Audit system and/or SystemTap to run this down. A quick search turned up this article:
[Finding the source of signals on Linux with strace, auditd, or systemtap](https://www.ibm.com/developerworks/community/blogs/aimsupport/entry/Finding_the_source_of_signals_on_Linux_with_strace_auditd_or_Systemtap)

**Comment by mbeeby** [comment]
Chris,

This is a big help -- I really appreciate it! Thanks. 

All there is to do now is wait for munge to die again.

thanks again. hopefully this will be enough for me to troubleshoot.

Morgan
