### ISSUE TITLE
CentOS 8 Incomplete Build

### ISSUE THREAD

**Issue by batainma** [dun/munge#72]
When attempting to build munge in a CentOS 8 environment, it seemingly goes well but later has missing directories and loss of functionality.

I am building from source following the guide I've always used and also other guides. There are no errors, simply the "munge/rc.d" directory is never created and the "munge.socket.2" is missing within "munge/run/munge".

Could you build and test this on CentOS 8 and see if this issue lies in my configuration or if there is a compatibility issue?

I've attached the config.log as well as a screenshot of me running 'ls' in all the directories sub-directories.

[config.log](https://github.com/dun/munge/files/4061413/config.log)

![Screenshot from 2020-01-14 14-53-13](https://user-images.githubusercontent.com/56236642/72381871-c3456a00-36dd-11ea-8e90-406c19cfdd90.png)

**Comment by dun** [comment]
CentOS 8 uses systemd, so the rc.d directory and init script aren't installed.

The attached `config.log` looks ok.

This appears to be an `ls` from `/node/local/services/munge/`. And its contents look correct for your `configure` line:
```
$ ./configure --prefix=/data/software/munge --sysconfdir=/node/local/services/munge --localstatedir=/node/local/services/munge
```

The `${localstatedir}/lib/munge/` directory will contain the PRNG seed file; that file will be created by munged when it is started.

The `${localstatedir}/log/munge/` directory will contain the log file; that file will be created by munged when it is started.

The `${localstatedir}/run/munge/` directory will contain the `munge.socket.2` socket and pid file; both of those are created by munged, and will only exist while the daemon is running.

The `${sysconfdir}/munge/` directory is empty because you haven't created a key yet (see `mungekey`). You might want to change your `sysconfdir`; `/node/local/services/munge/munge` seems odd to me. But it'll work just fine if that's what you want.

I've built and tested this on CentOS 8, and I'm not aware of any issues there.

By the way, 0.5.14 will hopefully be out by the end of the day. An updated installation guide should follow shortly thereafter.

**Comment by batainma** [comment]
First, thank you for the great response time!

Second, my apologies, I should've finished going through the steps before taking the screenshot.

Everything does look correct after generating a key and etc. 

The issue I had which is what originally led me to post this question was being unable to daemonize the service. I see now that it is located at /data/software/munge/lib/systemd/system/munge.service.

I'm moving a small cluster from CentOS 6 to CentOS 8 and it's been quite jarring. Thank you for your help, it looks like everything is working properly now.

**Comment by dun** [comment]
Glad I could be of help. Good luck on your upgrade.
