### ISSUE TITLE
0.5.13/14 OpenSUSE SPEC file refers to 0.5.11

### ISSUE THREAD

**Issue by pawsey-kbuckley** [dun/munge#81]
Long story (involving trying to build a Munge on SLES 15 that Slurm 20.02 can build against)
but I have seen that the tarball's

`extra/munge.spec-systemd-opensuse`

file, for both 0.5.13/14 has these five lines at the start

```
# Tested on:
# - openSUSE 12.3

Name:munge
Version:0.5.11
Release:1%{?dist}
```

which means that any attempt to do an rpmbuild against the SPEC-file 
wants to build against the 0.5.11 tarball, and a tar.bz2 version of that,
even though Munge's tarballs are now distriuted as tar,xz.

For completeness, the

`munge-0.5.13/extra/munge.spec-systemd-fedora`

file is similarly affected, but the 

`munge-0.5.14/extra/munge.spec-centos.6`

appears to be OK.

**Comment by dun** [comment]
I try to ensure that MUNGE builds and runs on as many distributions as I can test, but keeping up-to-date on all of their packaging standards is more than I can handle. The top-level `munge.spec` targets current CentOS since that is closest to what we run in production. In the past, I had tried to support multiple distributions using RPM conditionals but that became unwieldy when systemd gained widespread adoption.

When `munge.spec` was updated for 0.5.14, `extra/munge.spec-centos.6` was added in commit b6e763bc290220def3dea113f4266b4bcd4d5582 to support the sysvinit-based CentOS 6.

`extra/munge.spec-systemd-fedora` was removed in commit a8effe0b85e406d44031df303d8465c2004eaf96 since the top-level `munge.spec` worked for current CentOS & Fedora.

`extra/munge.spec-systemd-opensuse` should have been removed then since it is not being kept up-to-date. As noted in the comments, it was last tested for 0.5.11 on openSUSE 12.3. If you need a `munge.spec` for current openSUSE/SLES, try using the one maintained by [openSUSE](https://build.opensuse.org/package/view_file/openSUSE:Factory/munge/munge.spec?expand=1).

I'll push a commit to remove `extra/munge.spec-systemd-opensuse`.

**Comment by pawsey-kbuckley** [comment]
> I try to ensure that MUNGE builds and runs on as many distributions as I can test, but keeping up-to-date
> on all of their packaging standards is more than I can handle.

Just to say that there was no knock to you here, Chris and, FWIW, simply bumping
the version number and changing the bz2 toi xz in the Source line saw things work
as expected anyway.

Cheers for the link ot the OpenSUSE maintined version too. I feel your pain as
regards the plethora of packaging standards: in this case being told that I need
bzip2-devel when SUSE offers up libbz2-devel.

**Comment by dun** [comment]
@pawsey-kbuckley No worries. Sorry you had to run down a few dead ends, but glad you got it working.
