### ISSUE TITLE
problem with keyfile

### ISSUE THREAD

**Issue by jamesmememes** [dun/munge#96]
Hello, sorry to bother you, I was hoping you could help me with something, I already installed munge
when I run "systemctl status -l munge" it says its active and running, but apparently its not working properly

I went to this directory : "/usr/sbin" and runned the "munged" executable 
and this message pops up : failed to check keyfile "/etc/munge/munge.key": No such file or directory

could you please help me figure this out, I would really appreaciate it 

I installed munge using this commands 
  && cd munge-0.5.14          \
  && ./configure              \
     --prefix=/usr            \
     --sysconfdir=/etc        \
     --localstatedir=/var     \
     --runstatedir=/run       \
  && make                     \
  && make check               \
  && sudo make install

and had a problem but looking at your issues found the issue 92 witch helped me activate and run munge
https://github.com/dun/munge/issues/92

But I think Im missing something and thats why its not working properly. 

Pd: theres a posibility munge is working well, the think is, Im using it to run slurm and when I try to run the slurmd daemon it says : Unable to register: Protocol authentication error, thats why I think it has something to do with munge

**Comment by dun** [comment]
If `systemctl status -l munge` says it's active & running, try running `munge -n | unmunge`. This encodes & decodes a credential. If it works, then `munged` is working.

If you tried starting `munged` and got the error `failed to check keyfile "/etc/munge/munge.key": No such file or directory`, then you need to create a key. See [creating a key](../wiki/Installation-Guide#creating-a-key).

After you've created the key, that keyfile will need to be securely copied to all hosts within the cluster running `munged`. And `munged` on those hosts will need to be restarted in order to load the new key.

**Comment by jamesmememes** [comment]
Hello, this is the output
>munge -n | unmunge

munge: Error : Failed to access "/run/munge/munge.socket.2" : No such file
or directory
unmunge: Error: No credential specified

**Comment by dun** [comment]
OK, then `munged` isn't running. I think you just need to create a key, securely copy that key to other nodes in the cluster, and then restart `munged`.

**Comment by jamesmememes** [comment]
if I search for the munge.key file it says theres a key already
root@prueba:/etc# find / -iname 'munge.key'
/etc/munge/munge.key
/usr/local/etc/munge/munge.key

Im kinda confused should I just run the command : 
sudo -u munge ${sbindir}/mungekey --verbose
as the page says ?

**Comment by jamesmememes** [comment]
here are all the outputs Im getting in case it helps for something. 

prueba@prueba:~$ systemctl status -l munge
● munge.service - MUNGE authentication service
   Loaded: loaded (/usr/local/lib/systemd/system/munge.service; disabled; vendor
   Active: active (running) since mié 2021-03-03 20:19:35 CST; 17min ago
     Docs: man:munged(8)
  Process: 8225 ExecStart=/usr/local/sbin/munged $OPTIONS (code=exited, status=0
 Main PID: 8228 (munged)
   CGroup: /system.slice/munge.service
           └─8228 /usr/local/sbin/munged

mar 03 20:19:35 prueba systemd[1]: Stopped MUNGE authentication service.
mar 03 20:19:35 prueba systemd[1]: Starting MUNGE authentication service...
mar 03 20:19:35 prueba systemd[1]: Started MUNGE authentication service.
lines 1-12/12 (END)
prueba@prueba:~$ cd ../../usr/local/sbin/
prueba@prueba:/usr/local/sbin$ ./munged 
munged: Error: Failed to check logfile "/usr/local/var/log/munge/munged.log": Permission denied
prueba@prueba:/usr/local/sbin$ sudo ./munged 
[sudo] password for prueba: 
munged: Error: Logfile is insecure: "/usr/local/var/log/munge/munged.log" should be owned by UID 0 instead of UID 999
prueba@prueba:/usr/local/sbin$ munge -n | unmunge
munge: Error: Failed to access "/run/munge/munge.socket.2": No such file or directory
unmunge: Error: No credential specified
prueba@prueba:/usr/local/sbin$

**Comment by dun** [comment]
It kinda looks like you have two installations of munge on your system: one under /usr using `/etc/munge/munge.key`, and another under /usr/local using `/usr/local/etc/munge/munge.key`.

According to systemd, `/usr/local/sbin/munged` is running. But the `configure` command you listed above specified `--prefix=/usr`, so how did `munged` get installed under `/usr/local/`?

Since systemd reports `/usr/local/sbin/munged` is running, try: `/usr/local/bin/munge -n | /usr/local/bin/unmunge`

**Comment by jamesmememes** [comment]
yes, Im pretty sure it was because first I used only run the ./configure command, and installed it but didnt work, so then I tried changing the directories as I mentioned before 

the new output is still the same : 

prueba@prueba:~$ /usr/local/bin/munge -n | /usr/local/bin/unmunge 
munge: Error: Failed to access "/run/munge/munge.socket.2": No such file or directory
unmunge: Error: No credential specified
prueba@prueba:~$ 

it's weird because i installed it on another operative system only using 
./configure
make
make install
and everything worked properly, now Im trying to run it on ubuntu with a virtual machine, since I wanted to test slurm-web and I had to do a lot of different things to run it, as I mentioned before readying your issue 92.

**Comment by jamesmememescr** [comment]
hello, I think he's looking for the socket in another directory 

as you can see the file munge is trying to find is in this directory 

root@prueba:/usr/local/var/run/munge# ls
munged.pid  munge.socket.2  munge.socket.2.lock

and the message shows another one. 
root@prueba:/usr/local/var/run/munge# /usr/local/bin/munge -n | /usr/local/bin/unmunge 
munge: Error: Failed to access "/run/munge/munge.socket.2": No such file or directory
unmunge: Error: No credential specified
root@prueba:/usr/local/var/run/munge# 

but Im not sure what Im suppose to do, should I just move those files ? or is it a better way and just change the path from where munge search for those files.

**Comment by dun** [comment]
Having two installations of munge installed is making it difficult to troubleshoot, and it appears they are conflicting with each other. I'd recommend removing one of them.

systemd reports `munged` is running, so I presume it is really running. You should be able to see it in the `ps` listing (e.g., `ps auxw | grep munged`). If `munged` is running, it has a key and it is listening on a local socket. Its logfile defaults to `${localstatedir}/log/munge`, and `${localstatedir}` is determined by the `configure` options. This logfile will show the socket it is listening on (e.g., `Created socket "/run/munge/munge.socket.2"`). The default socket is shown in the `--help` output (`/usr/local/sbin/munged --help | grep socket=`).

The munge clients (e.g., `munge` and `unmunge`, and the `libmunge` library) communicate with `munged` over this socket. They use a default based on the `configure` arguments (`${runstatedir}/munge/munge.socket.2`), but this can be overridden with the `-S/--socket=` command-line option. You can specify the socket location shown in the `munged` log when creating a credential. Since it appears that you're running a `munged` configured with default values, I'm guessing its socket is `/usr/local/var/run/munge/munge.socket.2`, so you should be able to create a credential with `munge -n -S /usr/local/var/run/munge/munge.socket.2`.

When munge in configured, all of the executables are using the same default value for the `munged` socket location so they can communicate with one another. But since your two installations of munge are using different defaults, things are not working as they normally would.

**Comment by jamesmememescr** [comment]
Thank you so much man, I really appreciate your help, it seems like its finally working 

prueba@prueba:~/Desktop/munge/munge-0.5.14$ /usr/local/bin/munge -n | /usr/local/bin/unmunge
STATUS:          Success (0)
ENCODE_HOST:     prueba (127.0.1.1)
ENCODE_TIME:     2021-03-04 12:58:51 -0600 (1614884331)
DECODE_TIME:     2021-03-04 12:58:51 -0600 (1614884331)
TTL:             300
CIPHER:          aes128 (4)
MAC:             sha256 (5)
ZIP:             none (0)
UID:             prueba (1000)
GID:             prueba (1000)
LENGTH:          0

prueba@prueba:~/Desktop/munge/munge-0.5.14$ systemctl status -l munge
● munge.service - MUNGE authentication service
     Loaded: loaded (/usr/local/lib/systemd/system/munge.service; disabled; ve>
     Active: active (running) since Thu 2021-03-04 12:28:13 CST; 31min ago
       Docs: man:munged(8)
   Main PID: 66927 (munged)
      Tasks: 4 (limit: 2316)
     Memory: 1.9M
     CGroup: /system.slice/munge.service
             └─66927 /usr/local/sbin/munged

mar 04 12:28:13 prueba systemd[1]: Starting MUNGE authentication service...
mar 04 12:28:13 prueba systemd[1]: Started MUNGE authentication service.

thanks for the help, have a nice day.

**Comment by dun** [comment]
You're welcome. Glad you got it working.
